[build]

    publish = "public"

    command = "npx babel src --out-dir build --presets react-app/prod"

[dev]
    publish = "public"

    #Honestly forget this nonsense. 
    #Just use: npx babel src --watch public --out-dir build --presets react-app/prod
    #command = "npx babel src --out-dir build --presets react-app/prod"