[build]

    publish = "build"

    command = "npx babel public src --out-dir build --presets react-app/prod; copyfiles -u 1 public/* build;"

[dev]
    publish = "build"

    #Honestly forget this nonsense. 
    #Just use: npx babel src --watch public --out-dir build --presets react-app/prod
    #command = "npx babel src --out-dir build --presets react-app/prod"